spring:
  application:
    name: beam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teambeam
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: teambeam07@gmail.com
    password: kbjtjuqfhocpshhk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

logging:
  level:
    org.springframework.data.redis: DEBUG

jwt:
  secret: RJjAZR5j+wemQdNpd3XreAcM9yftv14Wfc2e5lFrNf3d6RSnqIYkybdqPTPepVaOqBdTq8xVSwHj5tF88msmZw==
  refreshSecret: LyqRq32qBcyF3uCCdDOziK52gzdhSjKsmuMtO7tnmpCdqcwwS9KxzwshCVNou4ml6qyRQqXz4DWwomCjtRZxEg==
  expiration: 604800
  refreshExpiration: 604800

kakao:
  client-id: 77cdffa48c591cce8c307afbe9c188d9
  redirect-uri: http://localhost:3000/oauth
