spring:
  application:
    name: beam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teambeam
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.springframework.data.redis: DEBUG
