spring:
  application:
    name: beam
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/krampoline?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis
    port: 6379
logging:
  level:
    org.springframework.data.redis: DEBUG