spring:
  application:
    name: beam
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/krampoline?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis
    port: 6379

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: teambeam07@gmail.com
    password: kbjtjuqfhocpshhk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

logging:
  level:
    org.springframework.data.redis: DEBUG

jwt:
  secret: RJjAZR5j+wemQdNpd3XreAcM9yftv14Wfc2e5lFrNf3d6RSnqIYkybdqPTPepVaOqBdTq8xVSwHj5tF88msmZw==
  refreshSecret: LyqRq32qBcyF3uCCdDOziK52gzdhSjKsmuMtO7tnmpCdqcwwS9KxzwshCVNou4ml6qyRQqXz4DWwomCjtRZxEg==
  expiration: 600
  refreshExpiration: 604800

kakao:
  client-id: 77cdffa48c591cce8c307afbe9c188d9
  redirect-uri: https://k0bf03acb7c00a.user-app.krampoline.com/oauth

management:
  endpoints:
    web:
      exposure:
        include: "shutdown"